#!/bin/bash
if [ "$2" == "" ] ; then
    echo "Usage: ./update-spider [username]@[host] [config]"
    exit 0
fi
DST=$1
go build .
ssh -q $DST -tt 'sudo service spider stop'  || exit
scp -C spider $DST:/tmp/ || exit
scp -C $2 $DST:/tmp/config.yaml || exit
ssh -q $DST -tt 'sudo cp /tmp/spider /etc/spider/spider' || exit
ssh -q $DST -tt 'sudo cp /tmp/config.yaml /etc/spider/config.yaml' || exit
ssh -q $DST -tt 'sudo service spider start'
